### ISSUE TITLE
Where did you read and get this ?

### ISSUE THREAD

**Issue by abdulbadii** [jleffler/soq#213]
Where did you read and get this reference / manual... I want its PDF too

**Comment by jleffler** [comment]
Please clarify which reference manual you are referring to.  I can't place what you're referring to.  Please give the page or file or location (URL) on GitHub that contains the reference to which you're referring.  Some of the manuals I have are antiques — UNIX 7th Edition manuals, for example, in their printed forms.  But since I don't know what you're referencing, it is hard to help.

**Comment by jleffler** [comment]
No response — nothing to fix.
